image: python:latest

cache:
  paths:
    - .env/

before_script:
  - python -V
  - pip install virtualenv
  - virtualenv .env
  - source .env/bin/activate
  - pip install -r requirements.txt
  - python -m seed.test

test:
  script:
  - python -m tests.functional
