image: python:latest

variables:
  BUILD_ENV: "test"

cache:
  paths:
    - .env/

before_script:
  - python -V
  - pip install virtualenv
  - virtualenv .env
  - source .env/bin/activate
  - pip install -r requirements.txt

test:
  script:
  - python -m tests.auth
