image: python:latest

variables:
  BUILD_ENV: "test"

cache:
  paths:
    - .env/

before_script:
  - python -V
  - pip install virtualenv
  - virtualenv .env
  - source .env/bin/activate
  - pip install -r requirements.txt
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - cat ~/.ssh/id_rsa

test:
  script:
  - python -m tests.auth
  - python -m tests.documents
  
stage_deploy:
  only:
  - master
  script:
  - git remote add staging bannon@ek512.benpaulhanna.com:/var/repo/ek512.git
  - git push staging master
